# Generated by Django 4.0.6 on 2022-08-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_orden', '0002_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orden.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_path', models.CharField(max_length=70)),
                ('nombre_real', models.CharField(max_length=30)),
                ('id_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orden.seguimiento')),
            ],
        ),
    ]
