# Generated by Django 4.0.6 on 2022-08-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orden', '0003_seguimientoavance_seguimientoarchivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seguimientoarchivos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'El nombre ingresado ya existe, debe ingresar uno distinto.'}, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
