# Generated by Django 4.0.6 on 2022-08-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orden', '0004_seguimiento_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='cant_dias_proy',
            new_name='cant_dias',
        ),
    ]
